### ISSUE TITLE
critical security issue

### ISSUE THREAD

**Issue by Diamondlord** [whitfin/dot-notes-js#6]
Hi, @whitfin 
Library ["it-each"](https://github.com/whitfin/it.each) is using this library "dot-notes" that has [critical security issue](https://github.com/advisories/GHSA-qr4m-jcvc-3382)

The link to source code of dot-notes in [npm repository](https://www.npmjs.com/package/dot-notes) is broken : https://github.com/whitfin/dot-notes.

I suggest to fix the link to the source code and the security issue and update both of libraries ;)

I see that there is already PR: https://github.com/whitfin/dot-notes-js/pull/5
Do you plan to merge it?

**Comment by whitfin** [comment]
See notes in #5.
